- name: Restart Windows Host
  hosts: all
  tasks:
    - name: Annouce Reboot
      ansible.builtin.debug:
        msg: "The current host is restarting now!"
    - name: Wait to restart
      ansible.builtin.pause:
        seconds: 3
    - name: Reboot the machine
      ansible.windows.win_reboot:
        msg: "Reboot initiated by the playbook"
        reboot_timeout: 130
