- name: Restart Host
  hosts: all
  become: true
  tasks:
    - name: Print Hello World message
      ansible.builtin.debug:
        msg: "The current host is restarting now!"
      ansible.builtin.pause:
        seconds: 5
    - name: Reboot the machine
      ansible.builtin.reboot:
        msg: "Reboot initiated by the playbook"
        reboot_timeout: 300
